# Generated by Django 3.0.8 on 2020-07-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='url',
        ),
        migrations.AddField(
            model_name='products',
            name='kkal',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество ккал'),
        ),
    ]
