# Generated by Django 3.0.8 on 2020-07-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200727_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='background',
            field=models.CharField(default=None, max_length=150, verbose_name='Цвет фона'),
        ),
    ]
