# Generated by Django 3.0.8 on 2020-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='background',
            field=models.CharField(default='зеленый', max_length=150, verbose_name='Цвет фона'),
        ),
    ]
