# Generated by Django 3.0.8 on 2020-07-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200727_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('category', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('background', models.CharField(max_length=150, verbose_name='Цвет фона')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('kkal', models.PositiveIntegerField(default=0, verbose_name='Количество ккал')),
                ('price', models.PositiveIntegerField(default=0, help_text='указывать сумму в рублях', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
